#!/bin/bash
#
# Using tar and scp to backup ~/projects
#
# typical usage: ./tar_projects.sh -e --scp -v && echo "exit code is $?"
# will execute tar for /home/chris/projects and on success will execute scp to chris@ThinkPad:c:/backups/       
#
BASENAME_SCRIPT=$(basename $0)
VERBOSE=false
HELP=false
DO_EXECUTE=false #do not execute the tar command

#default source dir
TAR_SOURCE_DIR_DEFAULT="/home/chris/projects"
TAR_SOURCE_DIR=$TAR_SOURCE_DIR_DEFAULT

#default target dir for the tar
TAR_TARGET_DIR_DEFAULT="/home/chris/backups/"

#default target dir
TAR_TARGET_DIR=$TAR_TARGET_DIR_DEFAULT

#default tar-file-name & flags
DATE=$(date '+%4Y%m%d') #fetch the YYYYmmdd of today()
TAR_FILE_NAME="projects_${DATE}.tar.gz"
TAR_DEFAULT_FLAGS="czf"
TAR_FLAGS=$TAR_DEFAULT_FLAGS
TAR_VERBOSE_FLAG="v"

#default for scp
DO_SCP=false
#SCP_HOST_LOC_DEFAULT="chris@ubuntu-vm:/home/chris/temp/"
SCP_HOST_LOC_DEFAULT="chris@ThinkPad:c:/backups/" #remark: '/ is used in the dos dir-path instead of '\' works fine
SCP_HOST_LOC=$SCP_HOST_LOC_DEFAULT

#script_exit_code: if all ok it is 0
let SCRIPT_EXIT_CODE=0
#NOT being used: $((SCRIPT_EXIT_CODE+1)) #hocus pocus to increment by 1
SCRIPT_EXIT_CODE_GENERAL=1
SCRIPT_EXIT_CODE_TAR=2
SCRIPT_EXIT_CODE_SCP=3

log() {
    echo -e "$BASENAME_SCRIPT, $1"
}

help() {
    echo "$0 usage:"
    echo "executing script without param:"
    echo -e "\tno tar and no scp is done"
    echo "typical usage: ./tar_projects.sh -e --scp -v && echo \"exit code is \$?\""
    echo -e "\tWill do the tar of tar_source_dir: $TAR_SOURCE_DIR to tar-file $TAR_FILE_NAME"
    echo -e "\tin tar_dest_dir: $TAR_TARGET_DIR if both the tar_source_dir and the tar_dest_dir exist."
    echo -e "\ntar command that will be used:"
    echo -e "\ttar $TAR_FLAGS$TAR_VERBOSE_FLAG $TAR_SOURCE_DIR $TAR_TARGET_DIR$TAR_FILE_NAME"
    echo -e "\nscp command that will be used:"
    echo -e "\tscp $TAR_TARGET_DIR$TAR_FILE_NAME $SCP_HOST_LOC"
    echo -e "\nRemarks:"
    echo -e "\tif tar_source_dir and/or tar_dest_dir do not exist the script shows an ERROR and exits."
    echo -e "\ttar-file is generated by the script as: projects_YYYYmmdd.tar.gz"
    echo -e "\texit-code of the script: 0: all ok; 1: general error; 2: error with tar; 3: error with scp"
    echo -e "\tscipt has very limited to no error handling; very limited to no testing of the script has been done" 
    echo -e "\nScript params:"
    echo -e "\t-h --help: this help"
    echo -e "\t-s <dir> --source <dir>: use the <dir> as the source dir for files to tar"
    echo -e "\t-t <dir> --target <dir>: use the <dir> as the target dir of the tar"
    echo -e "\t-v --verbose: show more info on script execution"
    echo -e "\t-y --yes -e --execute: run the tar command, and scp command if tar went fine"
	echo -e "\t--scp: do scp to windows host"
    echo -e "\ntypical usage: ./tar_projects.sh -e --scp -v && echo \"exit code is \$?\""
    exit 0;
}

OPTS=`getopt -o vhyes:t: --long verbose,help,yes,execute,source:,target:,scp -n 'parse-options' -- "$@"`

if [ $? != 0 ] ; then log "Failed parsing options." >&2 ; exit 1 ; fi

#echo "$OPTS"
eval set -- "$OPTS" #parses the string returned by getopt and puts them in positional params $1 $2 ...

while true; do
  case "$1" in
    -v | --verbose ) VERBOSE=true; shift ;;
    -h | --help )    HELP=true; help; shift ;;
    -y | --yes ) DO_EXECUTE=true; shift ;;
    -e | --execute ) DO_EXECUTE=true; shift ;;
    -s | --source ) TAR_SOURCE_DIR=$2; shift; shift ;; #Remark: NO error checking in case no $2
	--scp ) DO_SCP=true; shift ;;
    -t | --target ) TAR_TARGET_DIR=$2; shift; shift ;; #Remark: NO error checking in case no $2
    -- ) shift; break ;;
    * ) break ;;
  esac
done

#check if the $TAR_SOURCE_DIR exists
if [ ! -d "$TAR_SOURCE_DIR" ]; then
    log "\nERROR - TAR_SOURCE_DIR: $TAR_SOURCE_DIR does not exist. Exiting script."; exit 1;
fi

#check if the $TARGET_DIR already exists
if [ ! -d "$TAR_TARGET_DIR" ]; then
    log "\nERROR - TARGET_DIR: $TAR_TARGET_DIR does not exist. Exiting script."; exit 1;
fi


TAR_COMMAND="tar $TAR_FLAGS $TAR_TARGET_DIR$TAR_FILE_NAME $TAR_SOURCE_DIR"
SCP_COMMAND="scp $TAR_TARGET_DIR$TAR_FILE_NAME $SCP_HOST_LOC"

if $VERBOSE ; then
    TAR_FLAGS="$TAR_FLAGS$TAR_VERBOSE_FLAG"
    TAR_COMMAND="tar $TAR_FLAGS $TAR_TARGET_DIR$TAR_FILE_NAME $TAR_SOURCE_DIR"
    echo "------"
    echo "Verbose is ON"
    echo "BASENAME_SCRIPT: $BASENAME_SCRIPT"
    echo "Params:"
    echo -e "\tVERBOSE=$VERBOSE"
    echo -e "\tHELP=$HELP"
    echo -e "\tDO_EXECUTE=$DO_EXECUTE"
    echo -e "\tDO_SCP=$DO_SCP"
    echo -e "\ntar-source-dir: $TAR_SOURCE_DIR"
    echo -e "tar-target-dir: $TAR_TARGET_DIR"
	echo -e "tar-file-name: $TAR_FILE_NAME"
    echo -e "\ntar-command: $TAR_COMMAND"
    echo -e "scp-command: $SCP_COMMAND"
    echo "------"
else
    log "Verbose is OFF"
fi

if $DO_EXECUTE ; then
    TAR_EXECUTED=$($TAR_COMMAND)
    TAR_EXIT_CODE=$?
    if $VERBOSE ; then #if VERBOSE is true, then show what tar command printed out
        echo "output tar_executed: $TAR_EXECUTED"
        echo "<end tar>"
    fi
    #log "exit code tar: $TAR_EXIT_CODE"
    if [ "$TAR_EXIT_CODE" -ne 0 ]; then
        DO_EXECUTE=false #do not execute next steps
        log "ERROR - result of tar is NOT ok, tar exit code: $TAR_EXIT_CODE"
        SCRIPT_EXIT_CODE=$SCRIPT_EXIT_CODE_TAR
    else
        log "result of tar is ok"
    fi
else
    log "not doing tar"
fi

#scp-part: if the execution of tar went fine and scp needs to be done
if [ $DO_EXECUTE == true ] && [ $DO_SCP == true ] ; then
    SCP_EXECUTED=$($SCP_COMMAND)
    SCP_EXIT_CODE=$?
    if $VERBOSE ; then #if VERBOSE is true, then show what scp command printed out
        echo "output scp_executed: $SCP_EXECUTED"
        echo "<end scp>"
    fi
    #log "exit code scp: $SCP_EXIT_CODE"
    if [ "$SCP_EXIT_CODE" -ne 0 ]; then
        log "ERROR - result of scp is NOT ok, scp exit code: $SCP_EXIT_CODE"
        SCRIPT_EXIT_CODE=$SCRIPT_EXIT_CODE_SCP
    else
        log "result of scp is ok"
    fi
else
    log "not doing scp"
fi

log "all done."
exit $SCRIPT_EXIT_CODE